// Comprehensive Restaurant Menu Data with Real Food Images

const menuData = [
  // ==================== APPETIZERS ====================
  {
    name: "Caesar Salad",
    description: "Crisp romaine lettuce, parmesan cheese, croutons, and creamy Caesar dressing",
    price: 249,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&q=80",
    available: true,
    rating: 4.5,
    prepTime: 8,
    isVeg: true,
    spiceLevel: 0,
    popular: true
  },
  {
    name: "Crispy Spring Rolls",
    description: "Golden fried rolls filled with fresh vegetables and aromatic herbs",
    price: 199,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&q=80",
    available: true,
    rating: 4.3,
    prepTime: 10,
    isVeg: true,
    spiceLevel: 1
  },
  {
    name: "Garlic Bread Sticks",
    description: "Freshly baked bread sticks with garlic butter and herbs",
    price: 149,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1573140401552-3fab0b24f5c6?w=500&q=80",
    available: true,
    rating: 4.6,
    prepTime: 6,
    isVeg: true,
    spiceLevel: 0,
    popular: true
  },
  {
    name: "Chicken Wings",
    description: "Spicy buffalo wings served with ranch dip and celery sticks",
    price: 329,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=500&q=80",
    available: true,
    rating: 4.7,
    prepTime: 12,
    isVeg: false,
    spiceLevel: 2,
    popular: true
  },
  {
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and mozzarella",
    price: 229,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=500&q=80",
    available: true,
    rating: 4.4,
    prepTime: 8,
    isVeg: true,
    spiceLevel: 0
  },

  // ==================== MAIN COURSE ====================
  {
    name: "Margherita Pizza",
    description: "Classic Italian pizza with fresh tomatoes, mozzarella, and basil",
    price: 349,
    category: "main",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&q=80",
    available: true,
    rating: 4.8,
    prepTime: 18,
    isVeg: true,
    spiceLevel: 0,
    popular: true,
    chefSpecial: true
  },
  {
    name: "BBQ Chicken Pizza",
    description: "Smoky BBQ sauce, grilled chicken, onions, and melted cheese",
    price: 429,
    category: "main",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&q=80",
    available: true,
    rating: 4.7,
    prepTime: 20,
    isVeg: false,
    spiceLevel: 1,
    popular: true
  },
  {
    name: "Vegetable Biryani",
    description: "Fragrant basmati rice cooked with mixed vegetables and aromatic spices",
    price: 299,
    category: "main",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=80",
    available: true,
    rating: 4.6,
    prepTime: 22,
    isVeg: true,
    spiceLevel: 2,
    popular: true
  },
  {
    name: "Chicken Tikka Masala",
    description: "Tender chicken in creamy tomato-based curry with aromatic spices",
    price: 389,
    category: "main",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80",
    available: true,
    rating: 4.9,
    prepTime: 25,
    isVeg: false,
    spiceLevel: 2,
    chefSpecial: true,
    popular: true
  },
  {
    name: "Paneer Butter Masala",
    description: "Cottage cheese cubes in rich, creamy tomato gravy",
    price: 329,
    category: "main",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&q=80",
    available: true,
    rating: 4.7,
    prepTime: 20,
    isVeg: true,
    spiceLevel: 1,
    popular: true
  },
  {
    name: "Grilled Salmon",
    description: "Fresh Atlantic salmon with lemon butter sauce and seasonal vegetables",
    price: 599,
    category: "main",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&q=80",
    available: true,
    rating: 4.8,
    prepTime: 22,
    isVeg: false,
    spiceLevel: 0,
    chefSpecial: true
  },
  {
    name: "Pasta Alfredo",
    description: "Creamy fettuccine pasta with parmesan and garlic",
    price: 319,
    category: "main",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&q=80",
    available: true,
    rating: 4.5,
    prepTime: 16,
    isVeg: true,
    spiceLevel: 0
  },
  {
    name: "Lamb Rogan Josh",
    description: "Slow-cooked lamb in aromatic Kashmiri curry",
    price: 499,
    category: "main",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&q=80",
    available: true,
    rating: 4.8,
    prepTime: 28,
    isVeg: false,
    spiceLevel: 3,
    chefSpecial: true
  },

  // ==================== DESSERTS ====================
  {
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten chocolate center, served with vanilla ice cream",
    price: 199,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&q=80",
    available: true,
    rating: 4.9,
    prepTime: 12,
    isVeg: true,
    spiceLevel: 0,
    popular: true
  },
  {
    name: "Tiramisu",
    description: "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone",
    price: 229,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80",
    available: true,
    rating: 4.7,
    prepTime: 8,
    isVeg: true,
    spiceLevel: 0,
    popular: true
  },
  {
    name: "Gulab Jamun",
    description: "Soft milk dumplings soaked in sweet rose-flavored syrup",
    price: 129,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?w=500&q=80",
    available: true,
    rating: 4.6,
    prepTime: 5,
    isVeg: true,
    spiceLevel: 0
  },
  {
    name: "Cheesecake",
    description: "Creamy New York style cheesecake with berry compote",
    price: 249,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=500&q=80",
    available: true,
    rating: 4.8,
    prepTime: 10,
    isVeg: true,
    spiceLevel: 0,
    chefSpecial: true
  },
  {
    name: "Ice Cream Sundae",
    description: "Three scoops of premium ice cream with toppings and hot fudge",
    price: 179,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&q=80",
    available: true,
    rating: 4.5,
    prepTime: 6,
    isVeg: true,
    spiceLevel: 0
  },

  // ==================== BEVERAGES ====================
  {
    name: "Fresh Lime Soda",
    description: "Refreshing lime juice with soda and mint",
    price: 89,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=500&q=80",
    available: true,
    rating: 4.4,
    prepTime: 4,
    isVeg: true,
    spiceLevel: 0
  },
  {
    name: "Mango Smoothie",
    description: "Thick and creamy mango smoothie made with fresh mangoes",
    price: 129,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=500&q=80",
    available: true,
    rating: 4.7,
    prepTime: 5,
    isVeg: true,
    spiceLevel: 0,
    popular: true
  },
  {
    name: "Cappuccino",
    description: "Classic Italian coffee with steamed milk foam",
    price: 119,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&q=80",
    available: true,
    rating: 4.6,
    prepTime: 5,
    isVeg: true,
    spiceLevel: 0
  },
  {
    name: "Iced Tea",
    description: "Chilled black tea with lemon and fresh mint",
    price: 99,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&q=80",
    available: true,
    rating: 4.3,
    prepTime: 4,
    isVeg: true,
    spiceLevel: 0
  },
  {
    name: "Chocolate Milkshake",
    description: "Rich and creamy chocolate milkshake topped with whipped cream",
    price: 149,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&q=80",
    available: true,
    rating: 4.8,
    prepTime: 6,
    isVeg: true,
    spiceLevel: 0,
    popular: true
  },
  {
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice, no added sugar",
    price: 109,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&q=80",
    available: true,
    rating: 4.5,
    prepTime: 4,
    isVeg: true,
    spiceLevel: 0
  },
  {
    name: "Masala Chai",
    description: "Traditional Indian spiced tea with milk",
    price: 69,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80",
    available: true,
    rating: 4.6,
    prepTime: 5,
    isVeg: true,
    spiceLevel: 1
  }
];

module.exports = menuData;
